### ISSUE TITLE
Разобраться с дисковыми метриками Ganglia

### ISSUE THREAD

**Issue by evlinsky** [egorlitsky/Trend-prediction#6]
- Что значит каждая метрика?
- Как воздействовать на систему, чтобы она ворзрастала или убывала? (копировать файл или что-то еще)

**Comment by egorlitsky** [comment]
1.1. I/O Time its time idle waiting for I/O operations to complete;
1.2. Operations - count operations by operation type per time;
1.3. TimeOnDisk - time of the writing and reading oprations;
1.4. Data transferred  - read, written data in bytes / sec.
1. 1) Example with disks metrics:
   http://eastcirclek.blogspot.ru/2015/10/monitoring-disk-throughput-using-ganglia.html ;
2. 2) Configure python_modules:
   https://sachinsharm.wordpress.com/2013/08/19/setup-and-configure-ganglia-python-modules-on-centosrhel-6-3/ ;
3. 3) Python modules:
   https://github.com/ganglia/gmond_python_modules/tree/master/diskstat/examples .
